name: pull_request

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - .devcontainer/**
      - .vscode/**
      - docs/**
      - README.md
      - LICENSE
      - .gitignore
      - .github/workflows/**

jobs:
  pull_request:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: "rnacloud_runner"
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          show-progress: 'false'
          lfs: 'true'

      - name: Check free disk space
        run: df -h

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME .

      - name: Run tests
        run: ./run_tests.sh

      - name: Upload output artifacts
        uses: actions/upload-artifact@v7
        with:
          name: test_output
          path: tests/batch_run/output
          compression-level: 0
          retention-days: 7

      - name: Compare md5checksums with latest release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          GENOME_AND_ANNOTATION_VERSION: ${{ steps.new_version.outputs.tag }}
        run: |
          set -euo pipefail

          echo "🏷️ Get latest release tag"
          tag="$(gh release list --json isLatest,tagName -q '.[] | select(.isLatest == true) | .tagName')"
          echo "Latest release tag: $tag"

          # fetch md5checksums.txt from that tag in the repo (works for private repos)
          tmpfile="/tmp/md5checksums.txt"

          echo "⬇️ Downloading md5checksums.txt from release $tag ..."
          gh release download $tag -p 'md5checksums.txt' -O $tmpfile

          if [ ! -f $tmpfile ]; then
            echo "::error::No md5checksums.txt found at tag $tag."
            exit 1
          fi

          echo "🔎 Comparing files:"
          echo "--------------------------"
          echo "📃 Generated file (this run):"
          cat output/md5checksums.txt
          echo "--------------------------"
          echo "📃 Release file ($tag):"
          cat "$tmpfile"
          echo "--------------------------"

          # compare with the one produced in this run
          if cmp -s "output/md5checksums.txt" "$tmpfile"; then
            echo "::notice::= md5checksums for candidate release ${GENOME_AND_ANNOTATION_VERSION} matches the latest release ($tag)."
          else
            echo "::notice::≠ md5checksums for candidate release ${GENOME_AND_ANNOTATION_VERSION} differs from the latest release ($tag):"
            diff -u "$tmpfile" "output/md5checksums.txt" || true
          fi